routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('cms/admin')->group(function () {
    // Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    // Route::view('/specialities', 'admin.specialities')->name('admin.specialities');
    // Route::view('/doctors', 'admin.doctors')->name('admin.doctors');


    Route::view('/register', 'admin.register')->name('admin.register');
    Route::view('/forgot-password', 'admin.forgot-password')->name('admin.forgot-password');
    Route::view('/lock-screen', 'admin.lock-screen')->name('admin.lock-screen');

    Route::view('/error-404', 'admin.error-404')->name('admin.error-404');
    Route::view('/error-500', 'admin.error-500')->name('admin.error-500');

    Route::view('/blank', 'admin.temp')->name('admin.blank');

    Route::view('/tables-basic', 'admin.tables-basic')->name('admin.tables-basic');
    Route::view('/data-tables', 'admin.data-tables')->name('admin.data-tables');

    Route::view('/form-basic-inputs', 'admin.form-basic-inputs')->name('admin.form-basic-inputs');
    Route::view('/form-input-groups', 'admin.form-input-groups')->name('admin.form-input-groups');
    Route::view('/form-horizontal', 'admin.form-horizontal')->name('admin.form-horizontal');
    Route::view('/form-vertical', 'admin.form-vertical')->name('admin.form-vertical');
    Route::view('/form-mask', 'admin.form-mask')->name('admin.form-mask');
    Route::view('/form-validation', 'admin.form-validation')->name('admin.form-validation');
});

Route::prefix('cms/doctor')->group(function () {
    Route::view('/', 'doctor.dashboard')->name('doctor.dashboard');
    Route::view('/appointments', 'doctor.appointments')->name('doctor.appointments');
    Route::view('/my-patients', 'doctor.my-patients')->name('doctor.my-patients');
    Route::view('/schedule-timings', 'doctor.schedule-timings')->name('doctor.schedule-timings');
    Route::view('/invoices', 'doctor.invoices')->name('doctor.invoices');
    Route::view('/invoice-view', 'doctor.invoice-view')->name('doctor.invoice-view');
    Route::view('/reviews', 'doctor.reviews')->name('doctor.reviews');
    Route::view('/profile-settings', 'doctor.profile-settings')->name('doctor.profile-settings');
    Route::view('/social-media', 'doctor.social-media')->name('doctor.social-media');
    Route::view('/change-password', 'doctor.change-password')->name('doctor.change-password');
    //    Route::view('/', 'doctor.parent')->name('doctor.dashboard');
});

Route::prefix('cms/patient')->group(function () {
    Route::view('/', 'patient.dashboard')->name('patient.dashboard');
    Route::view('/change-password', 'patient.change-password')->name('patient.change-password');
    Route::view('/profile-settings', 'patient.profile-settings')->name('patient.profile-settings');
    Route::view('/favourites', 'patient.favourites')->name('patient.favourites');
});


// Route::get('check/name', function () {
//     return 'u can join';
// })->middleware('test');

Route::prefix('cms/admin')->namespace('Auth')->group(function () {
    Route::get('/login', 'AdminAuthController@LoginView')->name('admin.login');
    Route::post('/login', 'AdminAuthController@login');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::resource('admins', 'AdminController');
    Route::resource('cities', 'CityController');
    Route::resource('states', 'StateController');
    Route::resource('specialities', 'SpecialtyController');
    Route::resource('doctors', 'DoctorController');
    Route::view('/settings', 'admin.settings')->name('admin.settings');
    Route::view('/patients', 'admin.patients')->name('admin.patients');
    Route::view('/reviews', 'admin.reviews')->name('admin.reviews');
    Route::view('/transactions', 'admin.transactions')->name('admin.transactions');
    Route::view('/invoice-report', 'admin.invoice-report')->name('admin.invoice-report');
    Route::view('/profile', 'admin.profile')->name('admin.profile');
    Route::view('/appointments', 'admin.appointment-list')->name('admin.appointments');
    Route::view('/components', 'admin.components')->name('admin.components');
});
Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::get('cities/{id}/states', 'citycontroller@showStates')->name('cities.states');
});

app/Specialty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Specialty extends Model
{
    //
    public function doctor()
    {
        return $this->hasMany(Doctor::class, 'specialty_id', 'id');
    }
}

app/Http/Controllers/SpecialtyController.php
<?php

namespace App\Http\Controllers;

use App\Doctor;
use App\Specialty;
use createspecialtiestable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class SpecialtyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //
        // $specialties = Specialty::all();
        $specialties = Specialty::all();
        // $specialties = Specialty::withCount('Doctor')->get();
        return view('admin.specialties.index', ['Specialty' => $specialties]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $specialties = Specialty::all();
        $doctors = Doctor::all();
        return view('admin.specialties.create', ['doctor' => $doctors, 'Specialty' => $specialties]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'specialtyname' => 'required|string|min:3|max:20|unique:specialties,specialtyname',
            'status' => 'in:on',
            'specialty_image' => 'required|image',
        ]);
        $Specialty = new Specialty();
        $Specialty->specialtyname = $request->get('specialtyname');
        $Specialty->status = $request->has('status') ? 'Active' : 'InActive';

        if ($request->hasFile('specialty_image')) {
            $specialty_image = $request->file('specialty_image');
            $imageName = time() . '_' . $request->get('specialtyname') . '.' . $specialty_image->getClientOriginalExtension();
            $specialty_image->move('images/specialty', $imageName);
            $Specialty->specialty_image = $imageName;
        }

        $isSaved = $Specialty->save();
        if ($isSaved) {
            session()->flash('alert-type', 'alert-success');
            session()->flash('message', 'Specialty add successfully');
            return redirect()->back();
        } else {
            session()->flash('alert-type', 'alert-danger');
            session()->flash('message', 'failed to create Specialty');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $Specialty = Specialty::findOrFail($id);
        return view('admin.specialties.edit', ['Specialty' => $Specialty]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->request->add(['Specialty_id' => $id]);
        $request->validate([
            'Specialty_id' => 'required|integer|exists:specialties,id',
            'specialtyname' => 'required|string|min:3|max:20',
            'status' => 'in:on'
        ]);
        $Specialty = Specialty::find($id);
        $Specialty->specialtyname = $request->get('specialtyname');
        $Specialty->status = $request->has('status') ? 'Active' : 'InActive';
        $isUpdated = $Specialty->save();
        if ($isUpdated) {
            return redirect()->route('specialities.index');
        } else {
            return Redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $isDeleted = specialty::destroy($id);
        if ($isDeleted) {
            return response()->json(
                [
                    'title' => 'Success',
                    'text' => 'City Deleted Successfully',
                    'icon' => 'success',
                ],
                200
            );
        } else {
            return response()->json(
                [
                    'title' => 'Failed',
                    'text' => 'failed to delete city',
                    'icon' => 'error',
                ],
                400
            );
        }
    }
}

resources/views/admin/specialties/create.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">specialties Form</h4>
                    </div>
                    <div class="card-body">
                        @if ($errors->any)
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $error }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endforeach
                    @endif

                    @if (session()->has('alert-type'))
                    <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                        {{ session()->get('message') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                        <form action="{{ route('specialities.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Specialty Name</label>
                                        <input name="specialtyname" value="{{ old('specialtyname') }}" type="text" class="form-control">
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-3">Specialty image</label>
                                        <div class="col-md-12">
                                            <input name="specialty_image" value="{{ old('specialty_image') }}" class="form-control" type="file" accept="image/*">
                                        </div>
                                    </div>
                                    <div class="status-toggle">
                                        <label>Activity status</label>
                                        <div class="status-toggle">
                                            <input name="status" type="checkbox" id="status_1" class="check" checked>
                                            <label for="status_1" class="checktoggle">checkbox</label>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
@endsection

resources/views/admin/specialties/edit.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">

                    <h4 class="card-title">specialties Form</h4>
                </div>

                <div class="card-body">
                    @if ($errors->any)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $error }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endforeach
                @endif

                @if (session()->has('alert-type'))
                <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                    {{ session()->get('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <form  action="{{ route('specialities.update',[$Specialty->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                        <div class="form-group">
                            <label>Specialty Name</label>
                        <input name="specialtyname" value="{{ $Specialty->specialtyname }}" type="text" class="form-control">
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-3">Specialty img</label>
                            <div class="col-md-12">
                                <input class="form-control" type="file">
                            </div>
                        </div>
                        <div class="status-toggle">
                            <label>Activity status</label>
                            <div class="status-toggle">
                                <input name="status" type="checkbox" id="status_1" class="check"
                                @if ($Specialty->status === "Active")
                                    checked
                                @endif>
                                <label for="status_1" class="checktoggle">checkbox</label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
@endsection

resources/views/admin/specialties/index.blade.php
@extends('admin.parent')

@section('title','specialties')

@section('style')

@endsection

@section('page-title','specialties')
@section('page-breadcrumb','specialties')

@section('action')
    <div class="col-sm-5 col">
    <a href="{{ route('specialities.create') }}"  class="btn btn-primary float-right mt-2">Add Specialty</a>
    </div>
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-center mb-0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Image</th>
                                <th>specialties</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Doctors Count</th>
                                <th>Settings</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($Specialty as $specialties)
                            <tr>
                                <td>{{ $specialties->id }}</td>
                                <td>
                                    <div class="avatar avatar-lg">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{{ url('images/specialty/'.$specialties->specialty_image) }}">
                                    </div>
                                </td>
                                <td>{{ $specialties->specialtyname }}</td>
                                <td>{{ $specialties->status }}</td>
                                <td>{{ $specialties->created_at }}</td>
                                <td>
                                    {{$specialties->doctor_count}}  {{$specialties->doctor_count =($specialties->doctor_count > 1) ? 'doctors' : 'doctor'}}</a>
                                    </td>
                                <td>
                                    <a class="btn btn-sm bg-success-light"
                                           href="{{ route('specialities.edit',[$specialties->id]) }}">
                                            <i class="fe fe-pencil"></i> Edit
                                        </a>
                                    <a  onclick="confirmDelete(this,'{{ $specialties->id }}')" type="button" class="btn btn-sm bg-danger-light">
                                        <i class="fe fe-trash"></i> Delete</a>
                                </td>

                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="{{ asset('doccure/js/axios.js') }}"></script>
<script src="{{ asset('doccure/js/sweetalert.js') }}"></script>
<script>
    function confirmDelete (app, id){
    Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
        deleteCity(app,id);
  }
})
    }

    function deleteCity(app, id){
        axios.delete('/cms/admin/specialities/'+id)
    .then(function (response) {
        // handle success (200 - 300)
        console.log(response);
        app.closest('tr').remove();
        showMessage(response.data);
  })
    .catch(function (error) {
        // handle error (400-500)
        console.log(error.response.data);
  })
    .then(function () {
        // always executed
  });
    };

    function showMessage(data){
        Swal.fire({
            title: data.title,
            text: data.text,
            icon: data.icon,
            showConfirmButton: false,
            timer: 2000,
            }).then((result) => {
                    if (result.dismiss === Swal.DismissReason.timer) {
                    console.log('I was closed by the timer')
                }
            })
        }
    </script>
@endsection