routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('cms/admin')->group(function () {
    // Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    // Route::view('/specialities', 'admin.specialities')->name('admin.specialities');
    // Route::view('/doctors', 'admin.doctors')->name('admin.doctors');


    Route::view('/register', 'admin.register')->name('admin.register');
    Route::view('/forgot-password', 'admin.forgot-password')->name('admin.forgot-password');
    Route::view('/lock-screen', 'admin.lock-screen')->name('admin.lock-screen');

    Route::view('/error-404', 'admin.error-404')->name('admin.error-404');
    Route::view('/error-500', 'admin.error-500')->name('admin.error-500');

    Route::view('/blank', 'admin.temp')->name('admin.blank');

    Route::view('/tables-basic', 'admin.tables-basic')->name('admin.tables-basic');
    Route::view('/data-tables', 'admin.data-tables')->name('admin.data-tables');

    Route::view('/form-basic-inputs', 'admin.form-basic-inputs')->name('admin.form-basic-inputs');
    Route::view('/form-input-groups', 'admin.form-input-groups')->name('admin.form-input-groups');
    Route::view('/form-horizontal', 'admin.form-horizontal')->name('admin.form-horizontal');
    Route::view('/form-vertical', 'admin.form-vertical')->name('admin.form-vertical');
    Route::view('/form-mask', 'admin.form-mask')->name('admin.form-mask');
    Route::view('/form-validation', 'admin.form-validation')->name('admin.form-validation');
});

Route::prefix('cms/doctor')->group(function () {
    Route::view('/', 'doctor.dashboard')->name('doctor.dashboard');
    Route::view('/appointments', 'doctor.appointments')->name('doctor.appointments');
    Route::view('/my-patients', 'doctor.my-patients')->name('doctor.my-patients');
    Route::view('/schedule-timings', 'doctor.schedule-timings')->name('doctor.schedule-timings');
    Route::view('/invoices', 'doctor.invoices')->name('doctor.invoices');
    Route::view('/invoice-view', 'doctor.invoice-view')->name('doctor.invoice-view');
    Route::view('/reviews', 'doctor.reviews')->name('doctor.reviews');
    Route::view('/profile-settings', 'doctor.profile-settings')->name('doctor.profile-settings');
    Route::view('/social-media', 'doctor.social-media')->name('doctor.social-media');
    Route::view('/change-password', 'doctor.change-password')->name('doctor.change-password');
    //    Route::view('/', 'doctor.parent')->name('doctor.dashboard');
});

Route::prefix('cms/patient')->group(function () {
    Route::view('/', 'patient.dashboard')->name('patient.dashboard');
    Route::view('/change-password', 'patient.change-password')->name('patient.change-password');
    Route::view('/profile-settings', 'patient.profile-settings')->name('patient.profile-settings');
    Route::view('/favourites', 'patient.favourites')->name('patient.favourites');
});


// Route::get('check/name', function () {
//     return 'u can join';
// })->middleware('test');

Route::prefix('cms/admin')->namespace('Auth')->group(function () {
    Route::get('/login', 'AdminAuthController@LoginView')->name('admin.login');
    Route::post('/login', 'AdminAuthController@login');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::resource('admins', 'AdminController');
    Route::resource('cities', 'CityController');
    Route::resource('states', 'StateController');
    Route::resource('specialities', 'SpecialtyController');
    Route::resource('doctors', 'DoctorController');
    Route::view('/settings', 'admin.settings')->name('admin.settings');
    Route::view('/patients', 'admin.patients')->name('admin.patients');
    Route::view('/reviews', 'admin.reviews')->name('admin.reviews');
    Route::view('/transactions', 'admin.transactions')->name('admin.transactions');
    Route::view('/invoice-report', 'admin.invoice-report')->name('admin.invoice-report');
    Route::view('/profile', 'admin.profile')->name('admin.profile');
    Route::view('/appointments', 'admin.appointment-list')->name('admin.appointments');
    Route::view('/components', 'admin.components')->name('admin.components');
});
Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::get('cities/{id}/states', 'citycontroller@showStates')->name('cities.states');
});

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    //
    public function city()
    {
        return $this->belongsTo(City::class, 'city_id', 'id');
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\State;
use Illuminate\Http\Request;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $states = State::with('city')->paginate(5);
        return view('admin.states.index', ['states' => $states]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $cities = City::where('status', '=', 'Active')->get();
        return view('admin.states.create', ['cities' => $cities]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'city_id' => 'required|exists:cities,id',
            'name' => 'required|string|min:3|max:15',
            'status' => 'in:on|string',
        ], [
            'city_id.required' => 'Please, select city!',
            'name.required' => 'Enter state name',
        ]);
        $state = new State();
        $state->name = $request->get('name');
        $state->status = $request->has('status') ? 'Active' : 'InActive';
        $state->city_id = $request->get('city_id');
        $isSaved = $state->save();
        if ($isSaved) {
            session()->flash('alert-type', 'alert-success');
            session()->flash('message', 'State Add Successfully');
            return redirect()->back();
        } else {
            session()->flash('alert-type', 'alert-danger');
            session()->flash('message', 'Failed To Create State');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $cities = City::where('status', '=', 'Active')->get();
        $state = State::findOrFail($id);
        return view('admin.states.edit', ['cities' => $cities, 'state' => $state]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->request->add(['id' => $id]);
        $request->validate([
            'id' => 'required|integer|exists:states',
            'city_id' => 'required|exists:cities,id',
            'name' => 'required|string|min:3|max:10|unique:cities,name,' . $id,
            'status' => 'in:on'
        ]);
        $state = state::find($id);
        $state->name = $request->get('name');
        $state->status = $request->has('status') ? 'Active' : 'InActive';
        $state->city_id = $request->get('city_id');
        $isUpdated = $state->save();
        if ($isUpdated) {
            session()->flash('alert-type', 'alert-success');
            session()->flash('message', 'State Updated Successfully');
            return redirect()->back();
        } else {
            session()->flash('alert-type', 'alert-danger');
            session()->flash('message', 'Failed To Updat State');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $isDeleted = State::destroy($id);
        if ($isDeleted) {
            return response()->json(
                [
                    'title' => 'Success',
                    'text' => 'State Deleted Successfully',
                    'icon' => 'success',
                ],
                200
            );
        } else {
            return response()->json(
                [
                    'title' => 'Failed',
                    'text' => 'Failed To Delete State',
                    'icon' => 'error',
                ],
                400
            );
        }
    }
}

resources/views/admin/states/create.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">States Form</h4>
                </div>

                <div class="card-body">
                    @if ($errors->any)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $error }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endforeach
                @endif

                @if (session()->has('alert-type'))
                <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                    {{ session()->get('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <form action="{{ route('states.store') }}" method="POST">
                    @csrf
                    <div class="form-group row">
                        <label class="col-form-label col-lg-5"></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <select class="form-control" name="city_id">
                                        <option>-- Select City --</option>
                                        @foreach ($cities as $city)
                                            <option value="{{ $city->id }}">{{ $city->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <input name="name" value="{{ old('name') }}" type="text" class="form-control" placeholder="States Name">
                            </div>
                        </div>
                    </div>
                        <div class="status-toggle">
                            <label>Activity status</label>
                            <div class="status-toggle">
                                <input name="status" type="checkbox" id="status_1" class="check" checked>
                                <label for="status_1" class="checktoggle">checkbox</label>
                            </div>
                        </div>

                        <div class="text-right">
                            <button  type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
@endsection

resources/views/admin/states/edit.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">

                    <h4 class="card-title">States Form</h4>
                </div>

                <div class="card-body">
                    @if ($errors->any)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $error }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endforeach
                @endif

                @if (session()->has('alert-type'))
                <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                    {{ session()->get('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <form action="{{ route('states.update',[$state->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label>City</label>
                        <div class="md-4">
                            <select class="form-control" name="city_id">
                                <option>-- Select --</option>
                                @foreach ($cities as $city)
                                    <option value="{{ $city->id }}"
                                        @if ($state->city_id == $city->id)
                                        selected
                                        @endif
                                        >{{ $city->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                        <div class="form-group">
                            <label>State Name</label>
                        <input name="name" value="{{$state->name}}" type="text" class="form-control">
                        </div>
                        <div class="status-toggle">
                            <label>Activity status</label>
                            <div class="status-toggle">
                                <input name="status" type="checkbox" id="status_1" class="check"
                                @if ($state->status === "Active")
                                    checked
                                @endif>
                                <label for="status_1" class="checktoggle">checkbox</label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
@endsection

resources/views/admin/states/index.blade.php
@extends('admin.parent')

@section('title','States')

@section('style')
asdasd
@endsection

@section('page-title','States')
@section('page-breadcrumb','States')

@section('action')
    <div class="col-sm-5 col">
        <a href="{{ route('states.create') }}"  class="btn btn-primary float-right mt-2">Add State</a>
    </div>
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-center mb-0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>City</th>
                                <th>Created At</th>
                                <th>Settings</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($states as $state)
                            <tr>
                                <td>{{ $state->id }}</td>
                                <td>{{ $state->name }}</td>
                                <td>{{ $state->status }}</td>
                                <td>{{ $state->city->name }}</td>
                                <td>{{ $state->created_at }}</td>
                                <td>
                                    <a class="btn btn-sm bg-success-light"
                                           href="{{ route('states.edit',[$state->id]) }}">
                                            <i class="fe fe-pencil"></i> Edit
                                        </a>
                                        <a onclick="confirmDelete(this,'{{ $state->id }}')" type="button" class="btn btn-sm bg-danger-light">
                                            <i class="fe fe-trash"></i> Delete</a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row justify-content-center">
                    {{$states->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="{{ asset('doccure/js/axios.js') }}"></script>
<script src="{{ asset('doccure/js/sweetalert.js') }}"></script>


<script>
    function confirmDelete (app, id){
    Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
        deleteCity(app,id);
  }
})
    }

    function deleteCity(app, id){
        axios.delete('/cms/admin/states/'+id)
    .then(function (response) {
        // handle success (200 - 300)
        console.log(response);
        app.closest('tr').remove();
        showMessage(response.data);
  })
    .catch(function (error) {
        // handle error (400-500)
        console.log(error.response.data);
  })
    .then(function () {
        // always executed
  });
    };

    function showMessage(data){
        Swal.fire({
            title: data.title,
            text: data.text,
            icon: data.icon,
            showConfirmButton: false,
            timer: 2000,
            }).then((result) => {
                    if (result.dismiss === Swal.DismissReason.timer) {
                    console.log('I was closed by the timer')
                }
            })
        }
    </script>
@endsection