routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('cms/admin')->group(function () {
    // Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    // Route::view('/specialities', 'admin.specialities')->name('admin.specialities');
    // Route::view('/doctors', 'admin.doctors')->name('admin.doctors');


    Route::view('/register', 'admin.register')->name('admin.register');
    Route::view('/forgot-password', 'admin.forgot-password')->name('admin.forgot-password');
    Route::view('/lock-screen', 'admin.lock-screen')->name('admin.lock-screen');

    Route::view('/error-404', 'admin.error-404')->name('admin.error-404');
    Route::view('/error-500', 'admin.error-500')->name('admin.error-500');

    Route::view('/blank', 'admin.temp')->name('admin.blank');

    Route::view('/tables-basic', 'admin.tables-basic')->name('admin.tables-basic');
    Route::view('/data-tables', 'admin.data-tables')->name('admin.data-tables');

    Route::view('/form-basic-inputs', 'admin.form-basic-inputs')->name('admin.form-basic-inputs');
    Route::view('/form-input-groups', 'admin.form-input-groups')->name('admin.form-input-groups');
    Route::view('/form-horizontal', 'admin.form-horizontal')->name('admin.form-horizontal');
    Route::view('/form-vertical', 'admin.form-vertical')->name('admin.form-vertical');
    Route::view('/form-mask', 'admin.form-mask')->name('admin.form-mask');
    Route::view('/form-validation', 'admin.form-validation')->name('admin.form-validation');
});

Route::prefix('cms/doctor')->group(function () {
    Route::view('/', 'doctor.dashboard')->name('doctor.dashboard');
    Route::view('/appointments', 'doctor.appointments')->name('doctor.appointments');
    Route::view('/my-patients', 'doctor.my-patients')->name('doctor.my-patients');
    Route::view('/schedule-timings', 'doctor.schedule-timings')->name('doctor.schedule-timings');
    Route::view('/invoices', 'doctor.invoices')->name('doctor.invoices');
    Route::view('/invoice-view', 'doctor.invoice-view')->name('doctor.invoice-view');
    Route::view('/reviews', 'doctor.reviews')->name('doctor.reviews');
    Route::view('/profile-settings', 'doctor.profile-settings')->name('doctor.profile-settings');
    Route::view('/social-media', 'doctor.social-media')->name('doctor.social-media');
    Route::view('/change-password', 'doctor.change-password')->name('doctor.change-password');
    //    Route::view('/', 'doctor.parent')->name('doctor.dashboard');
});

Route::prefix('cms/patient')->group(function () {
    Route::view('/', 'patient.dashboard')->name('patient.dashboard');
    Route::view('/change-password', 'patient.change-password')->name('patient.change-password');
    Route::view('/profile-settings', 'patient.profile-settings')->name('patient.profile-settings');
    Route::view('/favourites', 'patient.favourites')->name('patient.favourites');
});


// Route::get('check/name', function () {
//     return 'u can join';
// })->middleware('test');

Route::prefix('cms/admin')->namespace('Auth')->group(function () {
    Route::get('/login', 'AdminAuthController@LoginView')->name('admin.login');
    Route::post('/login', 'AdminAuthController@login');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::resource('admins', 'AdminController');
    Route::resource('cities', 'CityController');
    Route::resource('states', 'StateController');
    Route::resource('specialities', 'SpecialtyController');
    Route::resource('doctors', 'DoctorController');
    Route::view('/settings', 'admin.settings')->name('admin.settings');
    Route::view('/patients', 'admin.patients')->name('admin.patients');
    Route::view('/reviews', 'admin.reviews')->name('admin.reviews');
    Route::view('/transactions', 'admin.transactions')->name('admin.transactions');
    Route::view('/invoice-report', 'admin.invoice-report')->name('admin.invoice-report');
    Route::view('/profile', 'admin.profile')->name('admin.profile');
    Route::view('/appointments', 'admin.appointment-list')->name('admin.appointments');
    Route::view('/components', 'admin.components')->name('admin.components');
});
Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::get('cities/{id}/states', 'citycontroller@showStates')->name('cities.states');
});

resources/views/admin/admins/create.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Admins Form</h4>
                    </div>
                    <div class="card-body">

                        @if ($errors->any)
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ $error }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endforeach
                    @endif

                    @if (session()->has('alert-type'))
                    <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                        {{ session()->get('message') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                        <form action="{{ route('admins.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <h4 class="card-title">Admin Information</h4>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        <input name="firstname" value="{{ old('firstname') }}" type="text" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        <input name="lastname" value="{{ old('lastname') }}" type="text" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input name="password" value="{{ old('password') }}" type="password" class="form-control">
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>City:</label>
                                                <select name="city_id" id="city_id" class="select" onchange="getcitystates()">
                                                    <option>Select City</option>
                                                    @foreach ($cities as $city)
                                                    <option value="{{$city->id}}">{{$city->name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>State:</label>
                                                <select name="state_id" id="state_id" class="select">
                                                    <option>Select State</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Gender:</label>
                                                <select name="gender" class="select">
                                                    <option>Select Gender</option>
                                                    <option value="Male">Male</option>
                                                    <option value="Female">Female</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Status:</label>
                                                <select name="status" class="select">
                                                    <option>Select Status</option>
                                                    <option value="Active">Active</option>
                                                    <option value="InActive">InActive</option>
                                                    <option value="Blocked">Blocked</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Birth Date</label><br>
                                        <input class="form-control" name="date" type="date"><br>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input name="email" value="{{ old('email') }}"
                                         type="text" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Mobile</label>
                                        <input name="mobile" value="{{ old('mobile') }}" type="text" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input name="admin_image" value="{{ old('image') }}" class="form-control" type="file" accept="image/*">
                                    </div>
                                </div>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
    <script>

        function getcitystates(){
            var selectCity = document.getElementById('city_id').value;
            var selectState = document.getElementById('state_id');
            selectState.length=0;

            @foreach($cities as $city)
            if(selectCity == '{{ $city->id }}'){
                @foreach($city->states as $state)
                    var option = document.createElement('option');
                    option.text = '{{ $state->name }}'
                    option.name = '{{$state->id}}'
                    selectState.add(option);
                @endforeach
            }
            @endforeach
        }
    </script>
@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.parent')

@section('title','Admins')

@section('style')

@endsection

@section('page-title','Admins')
@section('page-breadcrumb','Admins')

@section('action')
    <div class="col-sm-5 col">
    <a href="{{ route('admins.create') }}"  class="btn btn-primary float-right mt-2">Add</a>
    </div>
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-center mb-0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>State</th>
                                <th>Gender</th>
                                <th>Birth Date</th>
                                <th>Mobile</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Settings</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($admins as $admin)
                            <tr>
                                <td>{{ $admin->id }}</td>
                                <td>
                                    <div class="avatar avatar-lg">
                                        <img class="avatar-img rounded-circle" alt="User Image" src="{{ url('images/admin/'.$admin->admin_image) }}">
                                    </div>
                                </td>
                                <td>{{ $admin->firstname . " " . $admin->lastname  }}</td>
                                <td>{{ $admin->email }}</td>
                                <td>{{ $admin->state_id }}</td>
                                <td>{{ $admin->gender }}</td>
                                <td>{{ $admin->date }}</td>
                                <td>{{ $admin->mobile }}</td>
                                <td>{{ $admin->status }}</td>
                                <td>{{ $admin->created_at }}</td>
                                <td>
                                    <a class="btn btn-sm bg-success-light"
                                           href="{{ route('admins.edit',[$admin->id]) }}">
                                            <i class="fe fe-pencil"></i> Edit
                                        </a>
                                    <a  onclick="confirmDelete(this,'{{ $admin->id }}')" type="button" class="btn btn-sm bg-danger-light">
                                        <i class="fe fe-trash"></i> Delete</a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="{{ asset('doccure/js/axios.js') }}"></script>
<script src="{{ asset('doccure/js/sweetalert.js') }}"></script>
<script>
    function confirmDelete (app, id){
    Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
        deleteCity(app,id);
  }
})
    }

    function deleteCity(app, id){
        axios.delete('/cms/admin/admins/'+id)
    .then(function (response) {
        // handle success (200 - 300)
        console.log(response);
        app.closest('tr').remove();
        showMessage(response.data);
  })
    .catch(function (error) {
        // handle error (400-500)
        console.log(error.response.data);
  })
    .then(function () {
        // always executed
  });
    };

    function showMessage(data){
        Swal.fire({
            title: data.title,
            text: data.text,
            icon: data.icon,
            showConfirmButton: false,
            timer: 2000,
            }).then((result) => {
                    if (result.dismiss === Swal.DismissReason.timer) {
                    console.log('I was closed by the timer')
                }
            })
        }
    </script>
@endsection