routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('cms/admin')->group(function () {
    // Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    // Route::view('/specialities', 'admin.specialities')->name('admin.specialities');
    // Route::view('/doctors', 'admin.doctors')->name('admin.doctors');


    Route::view('/register', 'admin.register')->name('admin.register');
    Route::view('/forgot-password', 'admin.forgot-password')->name('admin.forgot-password');
    Route::view('/lock-screen', 'admin.lock-screen')->name('admin.lock-screen');

    Route::view('/error-404', 'admin.error-404')->name('admin.error-404');
    Route::view('/error-500', 'admin.error-500')->name('admin.error-500');

    Route::view('/blank', 'admin.temp')->name('admin.blank');

    Route::view('/tables-basic', 'admin.tables-basic')->name('admin.tables-basic');
    Route::view('/data-tables', 'admin.data-tables')->name('admin.data-tables');

    Route::view('/form-basic-inputs', 'admin.form-basic-inputs')->name('admin.form-basic-inputs');
    Route::view('/form-input-groups', 'admin.form-input-groups')->name('admin.form-input-groups');
    Route::view('/form-horizontal', 'admin.form-horizontal')->name('admin.form-horizontal');
    Route::view('/form-vertical', 'admin.form-vertical')->name('admin.form-vertical');
    Route::view('/form-mask', 'admin.form-mask')->name('admin.form-mask');
    Route::view('/form-validation', 'admin.form-validation')->name('admin.form-validation');
});

Route::prefix('cms/doctor')->group(function () {
    Route::view('/', 'doctor.dashboard')->name('doctor.dashboard');
    Route::view('/appointments', 'doctor.appointments')->name('doctor.appointments');
    Route::view('/my-patients', 'doctor.my-patients')->name('doctor.my-patients');
    Route::view('/schedule-timings', 'doctor.schedule-timings')->name('doctor.schedule-timings');
    Route::view('/invoices', 'doctor.invoices')->name('doctor.invoices');
    Route::view('/invoice-view', 'doctor.invoice-view')->name('doctor.invoice-view');
    Route::view('/reviews', 'doctor.reviews')->name('doctor.reviews');
    Route::view('/profile-settings', 'doctor.profile-settings')->name('doctor.profile-settings');
    Route::view('/social-media', 'doctor.social-media')->name('doctor.social-media');
    Route::view('/change-password', 'doctor.change-password')->name('doctor.change-password');
    //    Route::view('/', 'doctor.parent')->name('doctor.dashboard');
});

Route::prefix('cms/patient')->group(function () {
    Route::view('/', 'patient.dashboard')->name('patient.dashboard');
    Route::view('/change-password', 'patient.change-password')->name('patient.change-password');
    Route::view('/profile-settings', 'patient.profile-settings')->name('patient.profile-settings');
    Route::view('/favourites', 'patient.favourites')->name('patient.favourites');
});


// Route::get('check/name', function () {
//     return 'u can join';
// })->middleware('test');

Route::prefix('cms/admin')->namespace('Auth')->group(function () {
    Route::get('/login', 'AdminAuthController@LoginView')->name('admin.login');
    Route::post('/login', 'AdminAuthController@login');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::view('/', 'admin.dashboard')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminAuthController@logout')->name('admin.logout');
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::resource('admins', 'AdminController');
    Route::resource('cities', 'CityController');
    Route::resource('states', 'StateController');
    Route::resource('specialities', 'SpecialtyController');
    Route::resource('doctors', 'DoctorController');
    Route::view('/settings', 'admin.settings')->name('admin.settings');
    Route::view('/patients', 'admin.patients')->name('admin.patients');
    Route::view('/reviews', 'admin.reviews')->name('admin.reviews');
    Route::view('/transactions', 'admin.transactions')->name('admin.transactions');
    Route::view('/invoice-report', 'admin.invoice-report')->name('admin.invoice-report');
    Route::view('/profile', 'admin.profile')->name('admin.profile');
    Route::view('/appointments', 'admin.appointment-list')->name('admin.appointments');
    Route::view('/components', 'admin.components')->name('admin.components');
});
Route::prefix('cms/admin')->middleware('auth:admin')->group(function () {
    Route::get('cities/{id}/states', 'citycontroller@showStates')->name('cities.states');
});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    //
    public function states()
    {
        return $this->hasMany(State::class, 'city_id', 'id');
    }
}

app/Http/Controllers/API/CityController.php
<?php

namespace App\Http\Controllers\API;

use App\City;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cities = City::all();
        return response()->json([
            'status' => true,
            'message' => 'success',
            'cities' => $cities
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $city = City::findOrFail($id);
        $isDeleted = $city->delete();
        if ($isDeleted) {
            return response()->json([
                'status' => true,
                'message' => 'city deleted',
            ], 200);
        } else {
            return response()->json([
                'status' => false,
                'message' => 'Fail to delete city',
            ], 400);
        }
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use CreateCitiesTable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cities = City::withCount('states')->paginate(5);
        return view('admin.cities.index', ['cities' => $cities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        //
        $request->validate([
            'name' => 'required|string|min:3|max:10',
            'status' => 'in:on',
        ], [
            'name.required' => 'Enter city name',
            'name.string' => 'the city name must be string',
            'name.min' => 'name must be at least 3 character length',
            'name.max' => 'the max character length must be 10 character',
        ]);
        $city = new City();
        $city->name = $request->get('name');
        $city->status = $request->has('status') ? 'Active' : 'InActive';
        $isSaved = $city->save();
        if ($isSaved) {
            session()->flash('alert-type', 'alert-success');
            session()->flash('message', 'city add successfully');
            return redirect()->back();
        } else {
            session()->flash('alert-type', 'alert-danger');
            session()->flash('message', 'failed to create city');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $city = City::findOrFail($id);
        return view('admin.cities.edit', ['city' => $city]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->request->add(['city_id' => $id]);
        $request->validate([
            'city_id' => 'required|integer|exists:cities,id',
            'name' => 'required|string|min:3|max:10|unique:cities,name,' . $id,
            'status' => 'in:on'
        ]);
        $city = City::find($id);
        $city->name = $request->get('name');
        $city->status = $request->has('status') ? 'Active' : 'InActive';
        $isUpdated = $city->save();
        if ($isUpdated) {
            return redirect()->route('cities.index');
        } else {
            return Redirect()->back();
        }
    }



    public function destroy($id)
    {

        $isDeleted = City::destroy($id);
        if ($isDeleted) {
            return response()->json(
                [
                    'title' => 'Success',
                    'text' => 'City Deleted Successfully',
                    'icon' => 'success',
                ],
                200
            );
        } else {
            return response()->json(
                [
                    'title' => 'Failed',
                    'text' => 'failed to delete city',
                    'icon' => 'error',
                ],
                400
            );
        }
    }
    public function showStates($id)
    {
        $states = City::find($id)->states;
        return view('admin.states.index', ['states' => $states]);
    }
}

resources/views/admin/cities/create.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Cities Form</h4>
                </div>

                <div class="card-body">
                    @if ($errors->any)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $error }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endforeach
                @endif

                @if (session()->has('alert-type'))
                <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                    {{ session()->get('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <form action="{{ route('cities.store') }}" method="POST">
                    @csrf
                        <div class="form-group">
                            <label>Name</label>
                        <input name="name" value="{{ old('name') }}" type="text" class="form-control">
                        </div>
                        <div class="status-toggle">
                            <label>Activity status</label>
                            <div class="status-toggle">
                                <input name="status" type="checkbox" id="status_1" class="check" checked>
                                <label for="status_1" class="checktoggle">checkbox</label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button  type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
@endsection

resources/views/admin/cities/edit.blade.php
@extends('admin.parent')

@section('title','Dashboard')

@section('style')
    <link rel="stylesheet" href="{{asset('doccure/admin/assets/css/select2.min.css')}}">
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">

                    <h4 class="card-title">Cities Form</h4>
                </div>

                <div class="card-body">
                    @if ($errors->any)
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ $error }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endforeach
                @endif

                @if (session()->has('alert-type'))
                <div class="alert {{ session()->get('alert-type') }} alert-dismissible fade show" role="alert">
                    {{ session()->get('message') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @endif
                <form action="{{ route('cities.update',[$city->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                        <div class="form-group">
                            <label>Name</label>
                        <input name="name" value="{{$city->name}}" type="text" class="form-control">
                        </div>
                        <div class="status-toggle">
                            <label>Activity status</label>
                            <div class="status-toggle">
                                <input name="status" type="checkbox" id="status_1" class="check"
                                @if ($city->status === "Active")
                                    checked
                                @endif>
                                <label for="status_1" class="checktoggle">checkbox</label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


@endsection

@section('scripts')
    <script src="{{asset('doccure/admin/assets/js/select2.min.js')}}"></script>
@endsection

resources/views/admin/cities/index.blade.php
@extends('admin.parent')

@section('title','Cities')

@section('style')

@endsection

@section('page-title','Cities')
@section('page-breadcrumb','Cities')

@section('action')
    <div class="col-sm-5 col">
        <a href="{{ route('cities.create') }}"  class="btn btn-primary float-right mt-2">Add City</a>
    </div>
@endsection

@section('page-wrapper')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-center mb-0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Status</th>
                                <th>States Count</th>
                                <th>Created At</th>
                                <th>Settings</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($cities as $city)
                            <tr>
                                <td>{{ $city->id }}</td>
                                <td>{{ $city->name }}</td>
                                <td>{{ $city->status }}</td>
                                <td>
                                <a href="{{route('cities.states',$city->id)}}" type="button" class="btn btn-primary btn-sm active">
                                    {{$city->states_count}}  {{$city->states_count =($city->states_count > 1) ? 'states' : 'state'}}</a>
                                </td>
                                <td>{{ $city->created_at }}</td>
                                <td>
                                    <a class="btn btn-sm bg-success-light"
                                           href="{{ route('cities.edit',[$city->id]) }}">
                                            <i class="fe fe-pencil"></i> Edit
                                        </a>
                                        <a onclick="confirmDelete(this,'{{ $city->id }}')" type="button" class="btn btn-sm bg-danger-light">
                                            <i class="fe fe-trash"></i> Delete</a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row justify-content-center">
                    {{$cities->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
<script src="{{ asset('doccure/js/axios.js') }}"></script>
<script src="{{ asset('doccure/js/sweetalert.js') }}"></script>
{{-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script> --}}


<script>
    function confirmDelete (app, id){
    Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
        deleteCity(app,id);
  }
})
    }

    function deleteCity(app, id){
        axios.delete('/cms/admin/cities/'+id)
    .then(function (response) {
        // handle success (200 - 300)
        console.log(response);
        app.closest('tr').remove();
        showMessage(response.data);
  })
    .catch(function (error) {
        // handle error (400-500)
        console.log(error.response.data);
  })
    .then(function () {
        // always executed
  });
    };

    function showMessage(data){
        Swal.fire({
            title: data.title,
            text: data.text,
            icon: data.icon,
            showConfirmButton: false,
            timer: 2000,
            }).then((result) => {
                    if (result.dismiss === Swal.DismissReason.timer) {
                    console.log('I was closed by the timer')
                }
            })
        }
    </script>
@endsection